<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script src="js/main.js"></script>
        This is test
    </head>

    <body>
    	<form id="mainForm" action='#'>
    		<table id="mainTable">
    			<tr>
    				<td>URL:</td>
    				<td><input type="text" class="input" id="urltext"></td>
    			</tr>
    			<tr>
    				<td>Items:</td>
    				<td><input type="text" class="input" id="items"></td>
    			</tr>
    			<tr>
    				<td></td>
    				<td><button id="mainsubmit" class="btn" type="submit">Submit</button></td>
    			</tr>
    		</table>
    	</form>
    	<div id="response"></div>
    </body>
</html>